### ISSUE TITLE
NAMESPACE file needed.

### ISSUE THREAD

**Issue by serdar-eric** [nfdisco/fbdata#1]
Could you please exclude NAMESPACE line from .gitignore file. 
install_github() method under "devtools" looks for NAMESPACE file and building with rtools using "make" command under windows just became a headache..

**Comment by nfdisco** [comment]
Thanks. I've removed NAMESPACE and the *.Rd files from .gitignore. Can you try now, see if it works?

**Comment by serdar-eric** [comment]
It works now. Thanks.
